name: alaz
description: A powerful and customizable HTTP client for Dart and Flutter with support for retry, interceptors, caching, and more.
version: 1.0.0
homepage: https://github.com/oguzhan18/alaz

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
